# Generated by Django 4.1.1 on 2022-09-10 04:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(default=None, upload_to='media/product/%Y/')),
                ('photo2', models.ImageField(default=None, upload_to='media/product/%Y/')),
                ('photo3', models.ImageField(default=None, upload_to='media/product/%Y/')),
                ('product_name', models.CharField(max_length=255, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField()),
                ('after_discount_price', models.FloatField()),
                ('discount_amount', models.FloatField(default=False)),
                ('discount', models.CharField(default='0%', max_length=100)),
                ('original_price', models.FloatField(default=False)),
                ('category', models.CharField(choices=[('machinery', 'machinery'), ('crops', 'crops'), ('fertilizers', 'fertilizers'), ('seeds', 'seeds')], default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
