# Generated by Django 4.1.1 on 2022-09-10 07:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='after_discount_price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='description',
            field=ckeditor.fields.RichTextField(default=False),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='photo1',
            field=models.ImageField(default=False, upload_to='media/product/%Y/'),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='photo2',
            field=models.ImageField(default=False, upload_to='media/product/%Y/'),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='photo3',
            field=models.ImageField(default=False, upload_to='media/product/%Y/'),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='product_name',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
