# Generated by Django 4.1.1 on 2022-09-10 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_all_product_after_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='after_discount_price',
            field=models.FloatField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='description',
            field=ckeditor.fields.RichTextField(default=False, null=True),
        ),
    ]
