# Generated by Django 4.1.1 on 2022-09-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_all_product_after_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='discount',
            field=models.CharField(blank=True, default='0%', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='discount_amount',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='original_price',
            field=models.FloatField(blank=True, default=False),
        ),
    ]
