# Generated by Django 4.1.1 on 2022-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_all_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='original_price',
            field=models.FloatField(blank=True),
        ),
    ]
