# Generated by Django 4.1.1 on 2022-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_all_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_product',
            name='front_image',
            field=models.ImageField(default=False, upload_to='media/product/%Y/'),
        ),
    ]
