# Generated by Django 4.1.1 on 2022-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_all_product_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_product',
            name='stock',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='category',
            field=models.CharField(choices=[('machinery', 'machinery'), ('fertilizers', 'fertilizers'), ('seeds', 'seeds')], default='', max_length=255),
        ),
    ]
