# Generated by Django 4.1.1 on 2022-09-10 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=255)),
                ('last_name', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='none', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Received', 'Received')], default='In Progress', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('order_number', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('order_status', models.CharField(choices=[('Confirm', 'Confirm'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=255)),
                ('payment_status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=255)),
                ('order_made', models.IntegerField(blank=True, default=1, null=True)),
                ('shipping_method', models.CharField(blank=True, default='Standard Delivery', max_length=200, null=True)),
                ('delivery_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Received', 'Received')], default='In Progress', max_length=255)),
                ('refunded_amount', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=255, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, default='Failed', max_length=255, null=True)),
                ('payer_and_receiver', models.CharField(blank=True, default='Credit', max_length=255, null=True)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customer.customer')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='none', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('address1', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('state', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('shipping_method', models.CharField(blank=True, default=False, max_length=200, null=True)),
                ('shipping_same_as_billing', models.BooleanField(blank=True, default=False, null=True)),
                ('save_info_for_next_time', models.BooleanField(blank=True, default=False, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Payment Done', 'Payment Done')], default='Pending', max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('delivery_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.deliverystatus')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.all_product')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.shippingaddress')),
                ('transaction_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.all_product')),
            ],
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.order'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.shippingaddress'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.transaction'),
        ),
    ]
