# Generated by Django 4.1.1 on 2022-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
